name: Build Microservices Fase 2

on:
  push:
    branches:
      - feature/devsecops

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # =========================
      # CHECKOUT
      # =========================
      - name: Checkout fase 3
        uses: actions/checkout@v4

      # =========================
      # CLONE FASE 2
      # =========================
      - name: Clonar fase 2
        run: git clone https://github.com/nascied/tech-challenge-fase-2-fiap.git

      - name: Ver estrutura
        run: ls -R tech-challenge-fase-2-fiap

      # =========================
      # SETUP GO
      # =========================
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      # =========================
      # QUALITY CHECK (ANTES DO BUILD)
      # =========================
      - name: Vet & Format Auth
        run: |
          cd tech-challenge-fase-2-fiap/auth-service
          go vet ./...
          go fmt ./...

      - name: Vet & Format Evaluation
        run: |
          cd tech-challenge-fase-2-fiap/evaluation-service
          go vet ./...
          go fmt ./...

      # =========================
      # TESTS (ANTES DO BUILD)
      # =========================
      - name: Test Auth (Go)
        run: |
          cd tech-challenge-fase-2-fiap/auth-service
          go test ./...

      - name: Test Evaluation (Go)
        run: |
          cd tech-challenge-fase-2-fiap/evaluation-service
          go test ./...

      # =========================
      # BUILD (DEPOIS DOS TESTES)
      # =========================
      - name: Build Auth (Go)
        run: |
          cd tech-challenge-fase-2-fiap/auth-service
          go mod tidy
          go mod download
          go build .

      - name: Build Evaluation (Go)
        run: |
          cd tech-challenge-fase-2-fiap/evaluation-service
          go mod tidy
          go mod download
          go build .

      # =========================
      # PYTHON SERVICES (CHECK SIMPLES)
      # =========================
      - name: Teste serviços Python
        run: |
          python3 --version
          ls tech-challenge-fase-2-fiap/flag-service
          ls tech-challenge-fase-2-fiap/analytics-service
          ls tech-challenge-fase-2-fiap/targeting-service