name: Build Fase 2

on:
  push:
    branches:
      - feature/devsecops

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout fase 3
        uses: actions/checkout@v4

      - name: Clonar fase 2 (app)
        run: git clone https://github.com/nascied/tech-challenge-fase-2-fiap.git

      - name: Listar serviços
        run: ls -la tech-challenge-fase-2-fiap